[package]
name = "thinp"
version = "0.1.0"
authors = ["Joe Thornber <ejt@redhat.com>"]
edition = "2018"
license = "GPL3"

[dependencies]
atty = "0.2"
anyhow = "1.0"
base64 = "0.13"
byteorder = "1.4"
clap = "3.0"
crc32c = "0.6"
data-encoding = "2.3"
duct = "0.13"
fixedbitset = "0.4"
futures = "0.3"
flate2 = "1.0"
io-uring = "0.5"
indicatif = "0.16"
libc = "0.2"
nix = "0.23"
nom = "7.0"
num_cpus = "1.13"
num-derive = "0.3"
num-traits = "0.2"
quick-xml = "0.22"
rand = "0.8"
safemem = "0.3"
tempfile = "3.3"
threadpool = "1.8"
thiserror = "1.0"

[dev-dependencies]
json = "0.12"
quickcheck = "0.9"
quickcheck_macros = "0.9"
thinp_dev = { path = "../thinp_dev" }
