.TH CACHE_METADATA_SIZE 8 "Thin Provisioning Tools" "Red Hat, Inc."
.SH NAME
cache_metadata_size \- Estimate the size of the metadata device needed for a given configuration

.SH SYNOPSIS
.B cache_metadata_size
.RB [ options ]

.SH DESCRIPTION
.B cache_metadata_size
estimates the size of the metadata.  Either \-\-nr\-blocks, or \-\-block\-size
and \-\-device\-size must be specified.

.SH OPTIONS
.IP "\fB\-\-nr\-blocks\fP \<natural\>"
Specify the number of cache blocks.

.IP "\fB\-\-block-size\fP \<sectors\>"
Specify the size of each cache block in 512 byte sectors.

.IP "\fB\-\-device\-size\fP \<sectors\>"
Specify total size of the fast device used in the cache.  In 512 byte sectors.

.IP "\fB\-\-max\-hint\-width\fP \<nr bytes\>"
Cache policies use a per block 'hint' to record extra info (for instance hit
counts).  At the moment all policies use a 4 byte hint width.  If you want to use
a different hint width specify it with this switch.

.SH EXAMPLE
.B cache_metadata_size --nr-blocks 10240
.sp
.B cache_metadata_size --block-size 128 --device-size 1024000

.SH SEE ALSO
.B cache_dump(8)
.B cache_repair(8)
.B cache_restore(8)

.SH AUTHOR
Joe Thornber <ejt@redhat.com>
.br
Heinz Mauelshagen <heinzm@redhat.com>

