.TH CACHE_WRITEBACK 8 "Thin Provisioning Tools" "Red Hat, Inc." \" -*- nroff -*-
.SH NAME
cache_writeback \- writeback dirty blocks to the origin device.

.SH SYNOPSIS
.B cache_writeback
.RB [ options ]
.RB --metadata-device
.I {device|file}
.RB --origin-device
.I {device|file}
.RB --fast-device
.I {device|file}

.SH DESCRIPTION
.B cache_writeback

An offline tool that writesback dirty data to the data device
(origin).  Intended for use in recovery scenarios when the SSD is
giving IO errors.

This tool cannot be run on a live cache.

.SH OPTIONS

.IP "\fB\\-\-metadata\-device\fP \fI{device|file}\fP"
Location of cache metadata.

.IP "\fB\-\-origin\-device\fP \fI{device|file}\fP"
Slow device being cached.

.IP "\fB\-\-fast\-device\fP \fI{device|file}\fP"
Fast device containing the data that needs to be written back.

.IP "\fB\-\-skip\-metadata\-update\fP"
Do not update the metadata to clear the dirty flags for written back
data.  You may not want to do this if you're decommissioning the
cache.

.IP "\fB\-h, \-\-help\fP"
Print help and exit.

.IP "\fB\-V, \-\-version\fP"
Output version information and exit.

.SH SEE ALSO
.B cache_dump(8)
.B cache_check(8)
.B cache_repair(8)
.B cache_restore(8)

.SH AUTHOR
Joe Thornber <ejt@redhat.com>
