.TH THIN_LS 8 "Thin Provisioning Tools" "Red Hat, Inc." \" -*- nroff -*-
.SH NAME
thin_ls \- List thin volumes within a pool.

.SH SYNOPSIS
.B thin_ls
.RB [ options ]
.I {metadata device}

.SH DESCRIPTION
.B thin_ls
Displays infomation about thin volumes in a pool.  Pass the metadata device on the command line, not the
pool device.

This tool cannot be run on live metadata unless the \fB\-\-metadata\-snap\fP option is used.

.SH OPTIONS

.IP "\fB\-o, \-\-format\fP"
Give a comma separated list of the fields to be output.  Valid fields are:
DEV, MAPPED_BLOCKS, EXCLUSIVE_BLOCKS, SHARED_BLOCKS, MAPPED_SECTORS,
EXCLUSIVE_SECTORS, SHARED_SECTORS, MAPPED_BYTES, EXCLUSIVE_BYTES,
SHARED_BYTES, MAPPED, EXCLUSIVE, SHARED, TRANSACTION CREATE_TIME, SNAP_TIME

.IP "\fB\-\-no\-headers\fP"
Don't output headers.

.IP "\fB\-m, \-\-metadata\-snap\fP"

If you want to get information out of a live pool then you will need
to take a metadata snapshot and use this switch.

.IP "\fB\-\-verbose"
Provide extra information on the mappings.

.IP "\fB\-h, \-\-help\fP"
Print help and exit.

.IP "\fB\-V, \-\-version\fP"
Output version information and exit.

.SH SEE ALSO
.B thin_dump(8)
.B thin_repair(8)
.B thin_restore(8)
.B thin_rmap(8)
.B thin_trim(8)
.B thin_metadata_size(8)

.SH AUTHOR
Joe Thornber <ejt@redhat.com>
