.TH THIN_RESTORE 8 "Thin Provisioning Tools" "Red Hat, Inc." \" -*- nroff -*-
.SH NAME
thin_restore \- restore thin provisioning metadata file to device or file

.SH SYNOPSIS
.B thin_restore
.RB [ options ]
.RB -i
.I {device|file}
.RB -o
.I {device|file}

.SH DESCRIPTION
.B thin_restore
restores thin provisioning metadata created by the
respective device-mapper target dumped into an XML formatted (see
.BR thin_dump(8) )
.I file
, which optionally can be preprocessed before the restore to another
.I device
or
.I file.
If restored to a metadata
.I device
, the metadata can be processed by the device-mapper target.

.IP "\fB\-q, \-\-quiet\fP"
Suppress output messages, return only exit code.

.IP "\fB\-i, \-\-input\fP \fI{device|file}\fP"
Input file or device with metadata.

.IP "\fB\-o, \-\-output\fP \fI{device|file}\fP"
Output file or device.

.IP "\fB\-h, \-\-help\fP"
Print help and exit.

.IP "\fB\-V, \-\-version\fP"
Output version information and exit.

.SH EXAMPLE
Restores the XML formatted thin provisioning metadata on file
.B metadata
to logical volume /dev/vg/metadata for further processing by the
respective device-mapper target:
.sp
.B thin_restore -i metadata -o /dev/vg/metadata

.SH DIAGNOSTICS
.B thin_restore
returns an exit code of 0 for success or 1 for error.

.SH SEE ALSO
.B thin_dump(8)
.B thin_check(8)
.B thin_repair(8)
.B thin_rmap(8)
.B thin_metadata_size(8)

.SH AUTHOR
Joe Thornber <ejt@redhat.com>
.br
Heinz Mauelshagen <HeinzM@RedHat.com>
